# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "http://junsulee93.github.io"
baseurl:             "http://junsulee93.github.io"
paginate:            5

# About/contact
author:
  name:              Junsu Lee (Brian)
  url:               https://twitter.com/mdo
  email:             ljs93kr@gmail.com

# Custom vars
version:             1.0.1

# External gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
